export const CREATE_MOVIE = "CREATE_MOVIE";
export const CREATE_COMMENT = "CREATE_COMMENT";

export const SIGNUP_SUCCES = "SIGNUP_SUCCES";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const SIGNIN_SUCCES = "SIGNIN_SUCCES";
export const SIGNIN_ERROR = "SIGNIN_ERROR";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";

export const CREATE_PROJECT_ERROR = "CREATE_PROJECT_ERROR";
